---
sudo: required
language: python
services: docker

env:
  - version=">=2.4,<2.5" distro="alpine-latest" expectation="fail"
  - version=">=2.5,<2.6" distro="alpine-latest" expectation="fail"
  - version=">=2.6,<2.7" distro="alpine-latest" expectation="fail"
  - version=">=2.4,<2.5" distro="alpine-edge" expectation="fail"
  - version=">=2.5,<2.6" distro="alpine-edge" expectation="fail"
  - version=">=2.6,<2.7" distro="alpine-edge" expectation="fail"
  - version=">=2.4,<2.5" distro="archlinux" expectation="fail"
  - version=">=2.5,<2.6" distro="archlinux" expectation="fail"
  - version=">=2.6,<2.7" distro="archlinux" expectation="fail"
  - version=">=2.4,<2.5" distro="centos-6" expectation="fail"
  - version=">=2.5,<2.6" distro="centos-6" expectation="fail"
  - version=">=2.6,<2.7" distro="centos-6" expectation="fail"
  - version=">=2.4,<2.5" distro="centos-latest"
  - version=">=2.5,<2.6" distro="centos-latest"
  - version=">=2.6,<2.7" distro="centos-latest"
  - version=">=2.4,<2.5" distro="debian-latest" expectation="fail"
  - version=">=2.5,<2.6" distro="debian-latest" expectation="fail"
  - version=">=2.6,<2.7" distro="debian-latest" expectation="fail"
  - version=">=2.4,<2.5" distro="debian-stable" expectation="fail"
  - version=">=2.5,<2.6" distro="debian-stable" expectation="fail"
  - version=">=2.6,<2.7" distro="debian-stable" expectation="fail"
  - version=">=2.4,<2.5" distro="debian-unstable" expectation="fail"
  - version=">=2.5,<2.6" distro="debian-unstable" expectation="fail"
  - version=">=2.6,<2.7" distro="debian-unstable" expectation="fail"
  - version=">=2.4,<2.5" distro="fedora-latest" expectation="fail"
  - version=">=2.5,<2.6" distro="fedora-latest" expectation="fail"
  - version=">=2.6,<2.7" distro="fedora-latest" expectation="fail"
  - version=">=2.4,<2.5" distro="fedora-rawhide" expectation="fail"
  - version=">=2.5,<2.6" distro="fedora-rawhide" expectation="fail"
  - version=">=2.6,<2.7" distro="fedora-rawhide" expectation="fail"
  - version=">=2.4,<2.5" distro="opensuse-leap"
  - version=">=2.5,<2.6" distro="opensuse-leap"
  - version=">=2.6,<2.7" distro="opensuse-leap"
  - version=">=2.4,<2.5" distro="opensuse-tumbleweed" expectation="fail"
  - version=">=2.5,<2.6" distro="opensuse-tumbleweed" expectation="fail"
  - version=">=2.6,<2.7" distro="opensuse-tumbleweed" expectation="fail"
  - version=">=2.4,<2.5" distro="ubuntu-artful"
  - version=">=2.5,<2.6" distro="ubuntu-artful"
  - version=">=2.6,<2.7" distro="ubuntu-artful"
  - version=">=2.4,<2.5" distro="ubuntu-latest" expectation="fail"
  - version=">=2.5,<2.6" distro="ubuntu-latest" expectation="fail"
  - version=">=2.6,<2.7" distro="ubuntu-latest" expectation="fail"
  - version=">=2.4,<2.5" distro="ubuntu-devel" expectation="fail"
  - version=">=2.5,<2.6" distro="ubuntu-devel" expectation="fail"
  - version=">=2.6,<2.7" distro="ubuntu-devel" expectation="fail"

matrix:
  allow_failures:
    - env: version=">=2.4,<2.5" distro="alpine-edge" expectation="fail"
    - env: version=">=2.5,<2.6" distro="alpine-edge" expectation="fail"
    - env: version=">=2.6,<2.7" distro="alpine-edge" expectation="fail"
    - env: version=">=2.4,<2.5" distro="debian-unstable" expectation="fail"
    - env: version=">=2.5,<2.6" distro="debian-unstable" expectation="fail"
    - env: version=">=2.6,<2.7" distro="debian-unstable" expectation="fail"
    - env: version=">=2.4,<2.5" distro="fedora-rawhide" expectation="fail"
    - env: version=">=2.5,<2.6" distro="fedora-rawhide" expectation="fail"
    - env: version=">=2.6,<2.7" distro="fedora-rawhide" expectation="fail"
    - env: version=">=2.4,<2.5" distro="ubuntu-devel" expectation="fail"
    - env: version=">=2.5,<2.6" distro="ubuntu-devel" expectation="fail"
    - env: version=">=2.6,<2.7" distro="ubuntu-devel" expectation="fail"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install ansible"${version}"
  - pip install molecule
  - pip install docker

script:
  - if [ "${expectation}" = "fail" ] ; then ! molecule test --scenario-name "${distro}" ; else molecule test --scenario-name "${distro}" ; fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack: robertdebock:${slack_token}
  email: false
